import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { runInNewContext } from 'node:vm';
import { stripTypeScriptTypes } from 'node:module';
const source=readFileSync(new URL('../src/common/faceDiagnostics.ts',import.meta.url),'utf8');
const helper=stripTypeScriptTypes(source).replace(/^import .*;\r?\n/gm,'').replace(/^export /gm,'');
function state(){return runInNewContext(`${helper}\n;({faceDiagnosticState,faceDiagnosticNeedsAttention,recordFaceDiagnostic,diagnosticExportText});`,{reactive:(value:any)=>value,JSON});}
function report(extra:any={}){return {library_id:'lib',scope:'selection',total_faces:0,failed:0,diagnostics:{modelId:'antelope-v2',modelName:'AntelopeV2',parameters:{detection_threshold:.65,blur_threshold:200},detectedFaces:1,qualityFiltered:1,annotationSuppressed:0,storedRegions:0,manualRegions:0,failedImages:0,cachedImages:0,images:[{fileId:1,fileName:'portrait.heic',sourceSize:[4032,3024],pipeline:{decodedSize:[4096,3072],detectedFaces:1,qualityFiltered:1,samples:[{confidence:.85,blurScore:199.93791,state:'quality_filtered'}]},outcome:'quality_filtered'}]},...extra};}
test('quality-filtered detections are warnings, not successful no-face completions',()=>{const h=state();assert.equal(h.faceDiagnosticNeedsAttention(report()),true);assert.equal(h.recordFaceDiagnostic(report(),'lib'),true);assert.equal(h.faceDiagnosticState.visible,true);assert.equal(h.faceDiagnosticState.report.diagnostics.detectedFaces,1);});
test('annotation suppression, genuine detector misses and failures remain distinct',()=>{const h=state();for(const diagnostic of [{detectedFaces:0,cachedImages:0},{detectedFaces:1,annotationSuppressed:1},{detectedFaces:1,failedImages:1,startupError:'failed'}])assert.equal(h.faceDiagnosticNeedsAttention(report({diagnostics:diagnostic})),true);assert.equal(h.faceDiagnosticNeedsAttention(report({diagnostics:{detectedFaces:0,cachedImages:1}})),false);});
test('reports from other libraries are rejected and full-library jobs do not interrupt browsing',()=>{const h=state();assert.equal(h.recordFaceDiagnostic(report(),'other'),false);assert.equal(h.faceDiagnosticState.report,null);h.recordFaceDiagnostic(report({scope:'library'}),'lib');assert.equal(h.faceDiagnosticState.visible,false);});
test('copyable diagnostic text preserves exact threshold and near-boundary scores',()=>{const h=state();const text=h.diagnosticExportText(report());assert.match(text,/199\.93791/);assert.match(text,/blur_threshold/);assert.doesNotMatch(text,/embedding"|apiKey|credentialRevision/);});
test('detailed dialog includes models, dimensions, thresholds, stages, samples and export',()=>{const view=readFileSync(new URL('../src/components/FaceDiagnosticsDialog.vue',import.meta.url),'utf8');for(const key of ['thresholds','dimensions','error_stage','maximum_score','face_sample','quality_hint','heic_hint','copy'])assert.ok(view.includes(`face_diagnostics.${key}`));assert.match(view,/blurScore\.toFixed\(4\)/);assert.match(view,/fallbackReason/);});
test('completed jobs retain a reopenable report without changing model settings',()=>{const app=readFileSync(new URL('../src/main.js',import.meta.url),'utf8'),person=readFileSync(new URL('../src/components/Person.vue',import.meta.url),'utf8');assert.match(app,/recordFaceDiagnostic\(result/);assert.match(person,/face_diagnostics\.reopen/);assert.doesNotMatch(source,/update_ai|save_ai|config\.settings/);});
